# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c3f614f433b4d6830e223997c8abeb721d0d735e63bc89acc7ecb12b609a7d833887880071758420e7aad21ef1a350e05ebc02783ffee00429335d77d6c1d53

test:
  secret_key_base: 1085ee9e851dbe5a56109beeb38a978bba7df5d46678cad6a54cf5ad19718903e3b06c43665b120b4074f0f61bff0b70643fdc04268092cb495f9ee776c8a138

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
